### ISSUE TITLE
Some false positives

### ISSUE THREAD

**Issue by thistehneisen** [spyboy-productions/CloakQuest3r#4]
[+] Real IP Address of api.[redacted].com: 104.18.6.241
[+] Real IP Address of intranet.[redacted].com: 104.18.7.241

^ both are still Cloudflare

**Comment by thisisshubhamkumar** [comment]
It's mentioned in the readme file, it’s not a foolproof tool. 

- Sometimes it can't detect the real Ip.

- CloakQuest3r combines multiple indicators to uncover real IP addresses behind Cloudflare. While subdomain scanning is a part of the process, we do not assume that all subdomains' A records point to the target host. The tool is designed to provide valuable insights but may not work in every scenario. We welcome any specific suggestions for improvement. 

1. False Negatives: CloakReveal3r may not always accurately identify the real IP address behind Cloudflare, particularly for websites with complex network configurations or strict security measures.

2. Dynamic Environments: Websites' infrastructure and configurations can change over time. The tool may not capture these changes, potentially leading to outdated information.

3. Subdomain Variation: While the tool scans subdomains, it doesn't guarantee that all subdomains' A records will point to the primary host. Some subdomains may also be protected by Cloudflare.
